<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Book;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllBooks($filters = array())
    {
        $allBooksQueryBuilder = $this->getEntityManager()->getRepository(Book::class)
            ->createQueryBuilder('book')
            ->select('book,cat')
            ->innerJoin('book.category', 'cat')
            ->where('book.status = :status')
            ->setParameter('status', '1');
        return $allBooksQueryBuilder->getQuery()->getResult();
    }

    public function getBookArray($bookId)
    {
        $bookQueryBuilder = $this->getEntityManager()->getRepository(Book::class)
            ->createQueryBuilder('book');
        return $bookQueryBuilder->select('book')
            ->where('book.id= :id')
            ->setParameter('id', $bookId)
            ->getQuery()
            ->getResult(1);
    }
}
