<?php

namespace AppBundle\Repository;

/**
 * CategoryOfferRuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryOfferRuleRepository extends \Doctrine\ORM\EntityRepository
{
}
